'use strict';
const $=s=>document.querySelector(s),token=$('meta[name="api-token"]').content;
let report=null,csvText=null,runBusy=false,uploadBusy=false,uploadVersion=0;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
const date=s=>s.slice(0,10);
function error(message){$('#error').textContent=message;$('#error').hidden=!message}
async function request(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Scout-Token':token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed.');return value}
function cell(row,text,kind='td'){const c=document.createElement(kind);c.textContent=text;row.append(c);return c}
function list(target,items){target.replaceChildren();for(const text of items){const li=document.createElement('li');li.textContent=text;target.append(li)}}
function tone(el,value){el.classList.toggle('loss',value<0);el.classList.toggle('gain',value>=0)}
function chart(){const svg=$('#equity-chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();const paths=[report.combined.curve,report.benchmark_curve];const all=paths.flat();if(!all.length)return;
 const values=all.map(p=>p.equity),low=Math.min(...values),high=Math.max(...values),pad=Math.max(1,(high-low)*.15),ymin=low-pad,ymax=high+pad;
 const times=all.map(p=>Date.parse(p.timestamp)),xmin=Math.min(...times),xmax=Math.max(...times);
 const x=p=>57+(Date.parse(p.timestamp)-xmin)/(xmax-xmin||1)*720,y=n=>244-(n-ymin)/(ymax-ymin)*214;
 const make=(tag,attrs,text)=>{const node=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))node.setAttribute(k,String(v));if(text!==undefined)node.textContent=text;svg.append(node);return node};
 for(let k=0;k<5;k++){const value=ymin+(ymax-ymin)*k/4,py=y(value);make('line',{x1:57,x2:777,y1:py,y2:py,stroke:'#2c3e51','stroke-dasharray':'3 5'});make('text',{x:0,y:py+3,fill:'#7c94aa','font-size':9,'font-family':'monospace'},'$'+value.toFixed(0))}
 for(let i=1;i>=0;i--)make('path',{d:paths[i].map((p,k)=>(k?'L':'M')+x(p).toFixed(2)+','+y(p.equity).toFixed(2)).join(' '),fill:'none',stroke:i?'#bca0eb':'#8bd8b6','stroke-width':i?1.5:2.5});
 make('text',{x:57,y:269,fill:'#7c94aa','font-size':9,'font-family':'monospace'},date(report.split_at));make('text',{x:777,y:269,'text-anchor':'end',fill:'#7c94aa','font-size':9,'font-family':'monospace'},date(report.end));
}
function render(){const r=report,c=r.combined;
 $('#source-title').textContent=r.source==='synthetic_demo'?'INVENTED DEMO / NOT A PROFITABILITY CLAIM':'IMPORTED DATA / PROVENANCE NOT VERIFIED';
 $('#source-copy').textContent=r.source==='synthetic_demo'?'These assets and prices are fictional. Use them to check the workflow, then import real historical data.':'CSV loaded locally. Results depend on your timestamps, USD pricing, corporate-action adjustments and cost assumptions.';
 $('#data-period').textContent=date(r.start)+' → '+date(r.end);
 $('#net').textContent=money(c.net_profit);tone($('#net'),c.net_profit);$('#net-return').textContent=pct(c.net_return_pct)+' / estimated closeout equity '+money(c.final_equity);
 $('#drawdown').textContent=c.max_drawdown_pct.toFixed(2)+'%';$('#cost').textContent=money(c.fees_paid+c.slippage_cost+c.estimated_exit_cost);
 $('#risk').textContent=c.halted?'HALTED':'WITHIN LIMIT';$('#risk').classList.toggle('loss',c.halted);$('#risk-copy').textContent=c.halted?'Triggered '+date(c.halted_at)+'; exits wait for available bars.':'Entry caps active / '+(r.settings.max_drawdown*100).toFixed(0)+'% drawdown trigger';
 const comparisons=$('#comparison');comparisons.replaceChildren();for(const[key,label]of [['combined','Stocks + crypto'],['stocks_only','Stocks only'],['crypto_only','Crypto only'],['buy_and_hold','Buy & hold mix']]){const m=r.comparison[key],tr=document.createElement('tr');cell(tr,label);const ret=cell(tr,pct(m.net_return_pct));tone(ret,m.net_return_pct);cell(tr,m.max_drawdown_pct.toFixed(2)+'%');cell(tr,String(m.fill_count));comparisons.append(tr)}
 const candidates=$('#candidates');candidates.replaceChildren();for(const a of r.candidates){const tr=document.createElement('tr');if(a.selected)tr.classList.add('selected-row');const name=cell(tr,a.symbol+' / '+a.label);const tag=document.createElement('small');tag.textContent=a.asset_class.toUpperCase();name.append(tag);cell(tr,pct(a.training.net_return_pct));cell(tr,a.training.max_drawdown_pct.toFixed(2)+'%');cell(tr,pct(a.holdout_diagnostic.net_return_pct));cell(tr,a.selected?'TRAINING PICK':'Diagnostic');candidates.append(tr)}
 $('#selection-rule').textContent=r.selection_rule+' Holdout begins '+date(r.split_at)+'.';
 const selected=$('#selected');selected.replaceChildren();const labels={trend:'Trend',reversion:'Reversion',breakout:'Breakout',cash:'Cash'};for(const a of r.symbols){const row=document.createElement('div'),name=document.createElement('span'),small=document.createElement('small'),choice=document.createElement('strong');name.textContent=a.symbol;small.textContent=a.asset_class.toUpperCase()+' / '+a.bars+' BARS';name.append(small);choice.textContent=labels[a.selected_strategy];row.append(name,choice);selected.append(row)}
 const fills=$('#fills');fills.replaceChildren();if(!c.fills.length){const tr=document.createElement('tr'),td=cell(tr,'No fills. Staying in cash is a valid result.');td.colSpan=6;fills.append(tr)}for(const f of c.fills.slice(-300).reverse()){const tr=document.createElement('tr');cell(tr,date(f.timestamp));cell(tr,f.symbol);cell(tr,f.side.toUpperCase());cell(tr,f.quantity.toFixed(6));cell(tr,money(f.fill_price));cell(tr,money(f.fee));fills.append(tr)}
 $('#fill-caption').textContent='Showing latest '+Math.min(300,c.fills.length)+' of '+c.fills.length+' fills. Export JSON for full timestamps, assumptions, quantities and curves.';
 list($('#audit'),r.audit);list($('#limitations'),r.limitations);chart();$('#summarize').disabled=false;
}
function settings(){const value=id=>Number($('#'+id).value);return{capital:value('capital'),stock_weight:value('stock-weight')/100,crypto_weight:value('crypto-weight')/100,max_position:value('position-cap')/100,max_drawdown:value('drawdown-cap')/100,fees_bps:{stock:value('stock-fee'),crypto:value('crypto-fee')},slippage_bps:{stock:value('stock-slip'),crypto:value('crypto-slip')}}}
async function run(){if(runBusy||uploadBusy)return;runBusy=true;error('');$('#run-study').disabled=true;$('#reset-demo').disabled=true;$('#run-study').textContent='Testing…';try{const next=await request('/api/analyze',{settings:settings(),csv_text:csvText});report=next;$('#ai-notes').hidden=true;$('#ai-status').textContent='Optional. Review this report with an installed local model.';render()}catch(e){error(e.message+' Previous results are retained.')}finally{runBusy=false;$('#run-study').disabled=false;$('#reset-demo').disabled=false;$('#run-study').textContent='Run research'}}
$('#study-form').onsubmit=e=>{e.preventDefault();run()};
$('#csv').onchange=async()=>{const version=++uploadVersion;error('');const file=$('#csv').files[0];csvText=null;if(!file){uploadBusy=false;$('#run-study').disabled=runBusy;$('#reset-demo').disabled=runBusy;$('#file-state').textContent='No upload: deterministic invented demo.';return}if(file.size>1000000){uploadBusy=false;$('#run-study').disabled=runBusy;$('#reset-demo').disabled=runBusy;error('Use a CSV below 1 MB in this first version.');$('#csv').value='';$('#file-state').textContent='No upload: deterministic invented demo.';return}uploadBusy=true;$('#run-study').disabled=true;$('#reset-demo').disabled=true;try{const contents=await file.text();if(version!==uploadVersion)return;csvText=contents;$('#file-state').textContent=file.name+' loaded locally. Click Run research to test it.'}catch(e){if(version===uploadVersion)error('Could not read this CSV. Choose the file again.')}finally{if(version===uploadVersion){uploadBusy=false;$('#run-study').disabled=runBusy;$('#reset-demo').disabled=runBusy}}};
$('#reset-demo').onclick=()=>{uploadVersion++;uploadBusy=false;csvText=null;$('#csv').value='';$('#file-state').textContent='No upload: deterministic invented demo.';run()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))})});
$('#export-report').onclick=()=>{if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='Trading-Logic-Research-'+report.report_id+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#ai-form').onsubmit=async e=>{e.preventDefault();if(!report)return;const id=report.report_id;$('#summarize').disabled=true;$('#ai-status').textContent='Reading the report with your local model…';try{const result=await request('/api/summary',{model:$('#model').value,report_id:id});if(report.report_id!==result.report_id){$('#ai-status').textContent='Report changed; the older commentary was discarded.';return}$('#ai-summary').textContent=result.notes.summary;list($('#ai-risks'),result.notes.risks);list($('#ai-checks'),result.notes.next_checks);$('#ai-notes').hidden=false;$('#ai-status').textContent='Local model: '+result.notes.model+'. Commentary is unverified and has no execution authority.'}catch(err){$('#ai-status').textContent=err.message}finally{$('#summarize').disabled=false}};
$('#summarize').disabled=true;request('/api/report').then(r=>{report=r;render()}).catch(e=>error('Could not load the local research server. Run start-scout.bat and open http://127.0.0.1:8002. '+e.message));
